import type { WorkerTask } from '@maintenance-factory/types';

export function buildPRBody(task: WorkerTask, validationSummary: string): string {
  return `## Summary
<!-- What changed and why -->

## Maintenance Task
- Project item: ${task.projectItemId}
- Task type: \`${task.taskType}\`
- Risk: \`${task.risk}\`
- Repo criticality: \`${task.repoCriticality}\`

## Files Changed
<!-- Summarize modified files -->

## Validation
Commands run:
\`\`\`bash
${task.validationCommands?.join('\n') ?? 'pnpm test'}
\`\`\`

Results:
${validationSummary}

## Residual Risk
<!-- What reviewers should pay attention to -->

## Review Requirements
- CODEOWNER / repo owner review required
- Platform/security review may be required based on repo criticality

---
> **Agent Notice:** This PR was generated by a scheduled maintenance agent (template v${task.promptTemplateVersion}). It must be reviewed and merged manually.
`;
}
