import type { MaintenanceTask } from '@maintenance-factory/core';

export interface PrBodyInput {
  summary: string;
  task: MaintenanceTask;
  filesChanged: string[];
  commandsRun: string[];
  testResults: string;
  residualRisk: string;
  projectItemUrl?: string;
}

export function buildMaintenancePrBody(input: PrBodyInput): string {
  const t = input.task;
  return `## Summary
${input.summary}

## Maintenance Task
- Project item: ${input.projectItemUrl ?? '(link TBD)'}
- Task type: ${t.taskType}
- Severity: ${t.severity ?? 'n/a'}
- Risk: ${t.risk}
- Repo criticality: ${t.repoCriticality}

## Files Changed
${input.filesChanged.map((f) => `- ${f}`).join('\n')}

## Validation
Commands run:
\`\`\`bash
${input.commandsRun.join('\n')}
\`\`\`

Results:

${input.testResults}

## Residual Risk
${input.residualRisk}

## Review Requirements
- CODEOWNER / repo owner review
- Platform/security review, if required
- Senior review, if critical repo

## Agent Notice
This PR was generated by a scheduled maintenance agent. It must be reviewed and merged manually.

`;
}
